<a href="https://colab.research.google.com/github/konerulokesh25/ai-ml/blob/master/15_06_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import the packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [ ]:
## Importing the Dataset
data = pd.read_table("http://bit.ly/movieusers")
#data1 = pd.read_csv("http://bit.ly/movieusers")
data

1|24|M|technician|85711
0              2|53|F|other|94043
1             3|23|M|writer|32067
2         4|24|M|technician|43537
3              5|33|F|other|15213
4          6|42|M|executive|98101
..                            ...
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

[942 rows x 1 columns]

In [ ]:
data = pd.read_table("http://bit.ly/movieusers",sep="|")
data

1  24  M     technician  85711
0      2  53  F          other  94043
1      3  23  M         writer  32067
2      4  24  M     technician  43537
3      5  33  F          other  15213
4      6  42  M      executive  98101
..   ...  .. ..            ...    ...
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

[942 rows x 5 columns]

In [ ]:
data = pd.read_table("http://bit.ly/movieusers",sep="|",header=None)
data

0   1  2              3      4
0      1  24  M     technician  85711
1      2  53  F          other  94043
2      3  23  M         writer  32067
3      4  24  M     technician  43537
4      5  33  F          other  15213
..   ...  .. ..            ...    ...
938  939  26  F        student  33319
939  940  32  M  administrator  02215
940  941  20  M        student  97229
941  942  48  F      librarian  78209
942  943  22  M        student  77841

[943 rows x 5 columns]

# Handling the missing Values

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
df['temperature'].value_counts()

-99999    2
 32       2
 31       1
 28       1
 34       1
Name: temperature, dtype: int64

In [ ]:
df['temperature']

0       32
1   -99999
2       28
3   -99999
4       32
5       31
6       34
Name: temperature, dtype: int64

In [ ]:
df.day.dtype

dtype('O')

In [ ]:
type(df.day[0])

str

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [ ]:
#checking for duplicate values
df[df.duplicated()]

Empty DataFrame
Columns: [day, temperature, windspeed, event]
Index: []

In [ ]:
df['temperature'].duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
6    False
Name: temperature, dtype: bool

In [ ]:
#checking for duplicates specific temperature column 
df[df['temperature'].duplicated()]

day  temperature  windspeed event
3  1/4/2017       -99999          7     0
4  1/5/2017           32     -99999  Rain

In [ ]:
df[df['event'].duplicated()]

day  temperature  windspeed  event
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
df['event'].value_counts()

0        2
Sunny    2
Rain     2
Snow     1
Name: event, dtype: int64

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/weather_data.csv",parse_dates=['day'])
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02       -99999          7  Sunny
2 2017-01-03           28     -99999   Snow
3 2017-01-04       -99999          7      0
4 2017-01-05           32     -99999   Rain
5 2017-01-06           31          2  Sunny
6 2017-01-06           34          5      0

In [ ]:
df.day.dtype

dtype('<M8[ns]')

In [ ]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
new_df=df.replace({'temperature':-99999,'windspeed':-99999,'event':'0'},np.nan)
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0    NaN
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

## Imputation: Imputation is a process of substituting the missing values

In [ ]:
new_df.isnull()

day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False        False      False  False
6  False        False      False   True

In [ ]:
new_df.isnull().sum()

day            0
temperature    2
windspeed      2
event          2
dtype: int64

In [ ]:
# fillna() is a function which is used to fill the missing values
df1=new_df.fillna(0)#Shfit+tab 4 times to know the parmeters
df1

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          0.0        7.0  Sunny
2 2017-01-03         28.0        0.0   Snow
3 2017-01-04          0.0        7.0      0
4 2017-01-05         32.0        0.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0      0

In [ ]:
f_data=new_df.fillna(method='ffill')
f_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         28.0        7.0   Snow
4 2017-01-05         32.0        7.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0  Sunny

In [ ]:
## bfill -- backfill
b_data=new_df.fillna(method='bfill')
b_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         28.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         32.0        7.0   Rain
4 2017-01-05         32.0        2.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [ ]:
new_df.mean()

temperature    31.4
windspeed       5.4
dtype: float64

In [ ]:
## Mean Imputation
mean_data=new_df.fillna(new_df.mean())#fill the missing values in a column with the column's mean value
mean_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         31.4        7.0  Sunny
2 2017-01-03         28.0        5.4   Snow
3 2017-01-04         31.4        7.0    NaN
4 2017-01-05         32.0        5.4   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [ ]:
new_df.median()

temperature    32.0
windspeed       6.0
dtype: float64

In [ ]:
## Median Imputation
median_data=new_df.fillna(new_df.median())
median_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        6.0   Snow
3 2017-01-04         32.0        7.0    NaN
4 2017-01-05         32.0        6.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [ ]:
new_df.mode()

day  temperature  windspeed  event
0 2017-01-06         32.0        7.0   Rain
1        NaT          NaN        NaN  Sunny

In [ ]:
new_df.event.mode()

0     Rain
1    Sunny
dtype: object

In [ ]:
new_df.event.mode().iloc[0]

'Rain'

In [ ]:
new_df['event']=new_df['event'].fillna(new_df.event.mode().iloc[0])

new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0   Rain
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0   Rain

In [ ]:
#new_df['event']=new_df['event'].fillna(new_df.event.mode().iloc[1])
#new_df

Question 12:
Magic Square:

    19	7	19	93 -->dd mm cc yy
    94	18	4	22 -->yy+1 cc-1 mm-3 dd+3
    5	21	95	17 -->mm-2 dd+2 yy+2 cc-2
    20	92	20	6 --> cc+1 yy-1 dd+1 mm-1


In [ ]:
import numpy as np
arr1=np.array([[19,7,19,93],
             [94,18,4,22],
             [5,21,95,17],
             [20,92,20,6]])
print(arr1.sum(axis=1))#sum of the columns
print(arr1.sum(axis=0))#sum of the rows


[138 138 138 138]
[138 138 138 138]


In [ ]:
arr2=np.array([[19,3,19,99],
              [100,18,0,22],
              [1,21,101,17],
               [20,98,20,2]])
##
##
##
print(arr2.sum(axis=1))#sum of the columns
print(arr2.sum(axis=0))#sum of the rows


[140 140 140 140]
[140 140 140 140]


In [ ]:
arr2.trace(axis1=1,axis2=0)#forward diagonal

140

In [ ]:
arr2.trace(axis1=0,axis2=1)#backward diagonal

140

In [ ]:
#sum of the middle square 
s=0
for i in range(4):
    for j in range(4):
        if i!=0 and i!=3 and j!=0 and j!=3:
            s+=arr2[i,j]
print(s)
    

140


In [ ]:
#sum of the corner elements
arr2[0,0]+arr2[0,3]+arr2[3,0]+arr2[3,3]

140

In [ ]:
#forward and backward diagonals sum without trace
f=0
b=0
for i in range(4):
    for j in range(4):
        if i==j:
            f+=arr2[i,j]
        elif i+j ==3:
            b+=arr2[i,j]
print(f,b)            

140 140


In [ ]:
print(arr2[0,0]+arr2[0,1]+arr2[1,0]+arr2[1,1])

140
