<a href="https://colab.research.google.com/github/konerulokesh25/ai-ml/blob/master/Assignment_8(4_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#reverse of numpy array
import numpy as np
arr1=np.arange(12,37)
result=arr1[::-1]
result

array([36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20,
       19, 18, 17, 16, 15, 14, 13, 12])

In [2]:
#3 comparsion
a=np.array([0,10,20,30,40,50,60])
b=np.array([0,40])
print(np.in1d(a,b))

[ True False False False  True False False]


In [3]:
#2.Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
x = np.ones((5,5))
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
#4. Write a NumPy program to find the set difference of two arrays.
array1 = np.array([0, 10, 20, 40, 60, 80])
print(array1)
array2 = [10, 30, 40, 50, 70]
print(array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

[ 0 10 20 40 60 80]
[10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [5]:
#5.Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
x =  np.diagflat([4, 5, 6, 8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
